language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 7.0
  - 7.2
  - 7.4

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: phpunit --testsuite unit
